### ISSUE TITLE
Layout bug in Firefox 10+

### ISSUE THREAD

**Issue by SimonSteinberger** [mbi/django-rosetta#27] opened 2012-02-28 13:29 UTC
In Firefox version 10+ the translation table with all the message files is shifted to the right - as far as the end of the search form above. Please ad an overflow:hidden to #toolbar in rosetta.css to fix it:
# toolbar { height:20px;overflow: hidden}

Or place a <br style="clear: both;" /> below the toolbar <div> tag.

Thanks for the great app!!

**Comment by mbi** [comment] 2012-03-31 07:01
@Nasmon do you still see this? I just tested the latest version on Firefox 10 and 11, and on both versions all the pages seem to display correctly. Would you care to provide a screenshot and / or the PO file exposing the problem?

Thanks.

**Comment by SimonSteinberger** [comment] 2012-03-31 07:44
Hi mbi,

I just wanted to check, but with Django 1.4 and latest SVN of Rosetta, I can't open any language file. I get the the full list of languages in Rosetta, but when selecting one, the page only reloads and doesn't show the selected language messages. I'm pretty sure that is due to the new project layout of Django 1.4. The locations of manage.py / settings.py / locale directory have changed.

By the way two hopefully hints:

from django.conf.urls.defaults import url, patterns
is now:
from django.conf.urls import url, patterns

ADMIN_MEDIA_PREFIX is now deprecated and should be replaced with STATIC_ROOT (?)

I'll check the display bug and let you know as soon as Rosetta is running on our projects again :)

**Comment by mbi** [comment] 2012-03-31 19:05
@Nasmon I've tested Rosetta 0.6.6 against Django 1.4 and all tests passed and everything seemed OK. Also, what do you mean with "latest SVN of Rosetta"? Which version are you having issues with?

**Comment by SimonSteinberger** [comment] 2012-03-31 20:52
Hi mbi,
oops, I'm sorry about the ADMIN_MEDIA_PREFIX hint. I had an outdated version of Rosetta on our server ... however, selecting language files still doesn't work (latest Rosetta). With the new project layout of Django, there are different directory structures possible.

Our structure looks like this:
manage.py
--project
----settings.py
----urls.py
----locale
------en
------es
------fr
etc.

My test system is on Windows 7 - I couldn't check on our Ubuntu server, yet ...

**Comment by mbi** [comment] 2012-04-01 18:49
@Nasmon yes, I have tested against Django 1.4, including the new directory structure, and it works fine.

I'm going to close this bug, because we're discussing something completely different than the original issue (which I wasn't able to reproduce in the first place)

**Closed as completed by mbi** 2012-04-01 18:49 UTC

**Comment by SimonSteinberger** [comment] 2012-04-03 07:46
The display bug described in my original post is still present. Here's a screen shot of it:
http://content.imgbox.com/aat05yR2.png

Tested on Rosetta version 0.6.7, on Windows 7 and Firefox 10-12 consistently.

The error message you see on top of the screen shot is due to the fact, that I had to choose one of Django's write protected PO files. As also mentioned: selection of our project PO files is currently not working at all.

**Comment by mbi** [comment] 2012-04-03 10:14
Just tested on 0.6.7, Windows 7, Firefox 11 and couldn't reproduce this issue.
Is this on Django 1.4? Also, have you wiped your browser cache after you upgraded do 0.6.7 and/or Django 1.4?

**Comment by SimonSteinberger** [comment] 2012-04-03 11:13
Django 1.4, Rosetta 0.6.7, Windows 7, Firefox version 10+, possibly earlier, too (FF 9 and below untested), served from a LightTPD server.

Yes, cache, cookies and all settings have been fully cleared. Since I see that for over a month now, it's highly unlikely, that this is a cache problem or anything alike. I assume, it has something to do with installed fonts. Probably the div tag is off by only a few px due to slightly different font sizes when compared other systems. It's no big thing: a simple "overflow:hidden" in your style sheet fixes the problem. It's the easiest clearfix solution for that kind of breaking-problem and it's cross browser safe.

**Comment by Christophe31** [comment] 2013-07-15 09:10
Same bug here firefox nightly (25.0a), pip release of rosetta (0.7.2),
I'm using django 1.4.5, (because a bug with python 2.6 and django models with django 1.5)

http://pics.christophe31.net/photos/Screenshots/Screenshot_display_bug_rosetta.png

**Comment by sasha-medve** [comment] 2015-06-23 09:32
I can reproduce this issue now.

Python 2.7.6
Django==1.6.7
django-rosetta==0.7.4
+
Firefox 38.0
Ubuntu 14.04.2 LTS

Same screenshot
http://pics.christophe31.net/photos/Screenshots/Screenshot_display_bug_rosetta.png
