### ISSUE TITLE
Can't click language files from /rosetta/ in non chrome browser on osx.

### ISSUE THREAD

**Issue by ulchm** [mbi/django-rosetta#51] opened 2012-10-03 16:00 UTC
On the main listing page for the language files I can' click on a file to go to the next page.   It just reloads the current page over and over again,   I can make it go by repeatedly and rapidly clicking the link.

Chrome doesn't appear to have this issue but firefox and safari both do on OSX 10.8.  

THe link appears to go to http://<my_domain>.com/rosetta/select/fr/0/ however clicking it just reloads /rosetta/.

Have I included URLs improperly somewhere?

**Comment by ulchm** [comment] 2012-10-03 16:05
Update:

After I said this I started having hte same issue in chrome, leading me to believe it's some sort of misconfiguration with the URLS.    I also noticed that after I do get the link to work the url is still just /rosetta/  is that normal behaviour?

**Comment by JimmyVT** [comment] 2012-11-06 16:01
I'm using python2.7, django1.4 and developing in OSX 10.6 and have the exact same issue. Has anybody found a workaround this?

**Comment by mbi** [comment] 2012-11-06 17:20
Hi.

First off, it's normal that the url changes back to /rosetta/ after you've selected a language, that's normal behaviour. I've just tried reproducing this issue with Firefox and Safari, but both let me edit my translations as expected.

I wonder if this could be a server-side cache issue… could both of you please be a little more specific on how you're serving your Django? I.e. is this on the dev server, or an actual "real" server (nginx, apache)? 

Also, is django.middleware.cache.UpdateCacheMiddleware in your settings.MIDDLEWARE_CLASSES? And if yes, what is the value of settings.CACHE_MIDDLEWARE_ANONYMOUS_ONLY?

Thanks for your help debugging this.

**Comment by JimmyVT** [comment] 2012-11-06 17:45
Hi,

I'm on the dev server and 'django.middleware.cache.UpdateCacheMiddleware' is not in my settings.MIDDLEWARE_CLASSES. 

I've only added ROSETTA_STORAGE_CLASS = 'rosetta.storage.CacheRosettaStorage' to my settings.py file.

On a side note, what I ended up doing (to move forward with my translations) was to install the previous django-rosetta version ( 0.6.6 ) and things work as expected.

**Comment by mbi** [comment] 2012-11-06 17:57
Alright, even with ROSETTA_STORAGE_CLASS = 'rosetta.storage.CacheRosettaStorage'  I can't really reproduce this. What is your CACHE backed, pray tell?

**Comment by JimmyVT** [comment] 2012-11-06 18:07
Hmm... I've set my cache as follows:

CACHES = {
    'default': {
        'BACKEND':
        'django.core.cache.backends.memcached.MemcachedCache',
        'LOCATION': '127.0.0.1:11211',
    }
}

is that what you mean?

**Comment by mbarkhau** [comment] 2012-11-15 15:32
I am also having this issue and do not have any kind of caching configured.

**Comment by kitsunde** [comment] 2012-12-03 03:53
Me too. It seems like the user needs to double click the language to get to it for reasons beyond me.

**Comment by mbi** [comment] 2013-01-09 13:46
Darn, I'm really struggling trying to reproduce this bug.

I'm testing with:

``` python
ROSETTA_STORAGE_CLASS = 'rosetta.storage.CacheRosettaStorage'

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
        'LOCATION': '127.0.0.1:11222',
        'KEY_PREFIX': 'ROSETTA_TEST'
    }
}

```

Rosetta 0.6.8, Django (1.3.5, 1.4.2, 1.5c1) … and all my tests pass. 

EDIT: Chrome, Firefox, Safari on OS X 10.8.2

**Comment by kitsunde** [comment] 2013-01-09 14:15
I hadn't set `CACHE` when I was testing this. Also I was running two different (somewhat recent) versions of nginx (dev and prod).

**Comment by mbi** [comment] 2013-01-09 14:17
@Celc no cache set up defaults to LocMem AFAIK, so it should work… I'm writing additional tests, I'd love to get you to test the latest HEAD (in a few minutes)

**Comment by kitsunde** [comment] 2013-01-09 14:18
Also my client was reporting this issue on Windows, I was just confirming it on OSX. I probably can't test anything until tomorrow.

**Comment by mbi** [comment] 2013-01-09 14:27
Thanks, I really appreciate your help. I just committed bb0c774ed8e14733f5bf81fdf489bfd1e12ce6a9. You will probably get an ImproperlyConfigured error, it'll be interesting to see which specific test fails.

**Comment by mbi** [comment] 2013-01-15 12:56
Anyone willing to re-reproduce this with the latest commits? I'd really like to fix this issue before Django 1.5 lands to release a compatible point release. Cheers.

**Comment by ludovic-gasc** [comment] 2013-01-22 18:03
Hi,

if I add rosetta on a project where CACHES isn't defined in the settings.py, I've also this bug.
If I add in my settings.py: ROSETTA_STORAGE_CLASS = 'rosetta.storage.SessionRosettaStorage', now it works has excepted.

@mbi: I've installed rosetta from github, I've no errors in the Gunicorn logs.

Regards.

**Comment by mbi** [comment] 2013-01-22 19:09
Thanks @GMLudo.

I think I see where your particular problem lies: gunicorn spawns multiple processes, and each process has its own LocMem cache instance (the default backend if you define none) so this would make sense: one process writes and another one reads the content but finds none.

Is anyone here experiencing this using the stock (single-process) runserver development server?

**Comment by thongly** [comment] 2013-02-20 04:29
I WAS also getting this on Ubuntu 12.04 on both Chrome and Firefox. I am using Rosetta 0.6.8 with memcache on a production server.

HOWEVER... As with GMLudo, after excplicitly declaring the ROSETTA_STORAGE_CLASS...

ROSETTA_STORAGE_CLASS = 'rosetta.storage.SessionRosettaStorage'

and then restarting, it is fine. This leads to me to believe it is how the default is being treated when nothing is explicitly declared.

**Comment by mrooney** [comment] 2013-02-25 22:06
I ran into this as well, until I upgraded to the latest HEAD which raised an ImproperlyConfigured because I had specified the wrong CACHES['default']['LOCATION']. Thanks for adding that!

**Comment by Glideh** [comment] 2013-12-23 10:21
I confirm I can reproduce the issue in my mod_wsgi prod server but not with the default Django dev one.
With `ROSETTA_STORAGE_CLASS = 'rosetta.storage.CacheRosettaStorage'` or not

**Comment by Glideh** [comment] 2013-12-23 12:59
Fixed with

``` python
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
        'LOCATION': '127.0.0.1:11211',
        'KEY_PREFIX': 'ROSETTA_TEST'
    }
}
```

**Comment by mbi** [comment] 2013-12-23 13:00
@Glideh thanks, what was your CACHES before the fix?

**Comment by Glideh** [comment] 2013-12-23 13:02
None defined

**Comment by mbi** [comment] 2013-12-23 13:06
Alright, thanks everyone. Proper CACHES is needed, as clearly stated in the readme.

**Closed as completed by mbi** 2013-12-23 13:06 UTC

**Comment by gabejackson** [comment] 2013-12-29 14:47
This is not CLEARLY stated in the README.

**Comment by mbi** [comment] 2013-12-29 16:22
@gabejackson it says "if you run Django with gunincorn, mod-wsgi or other multi-process environment, the Django-default CACHES LocMemCache backend won't suffice: use memcache instead, or you will run into issues."

Now, I'm not a native speaker of English, so any suggestion on how to rephrase that sentence (or any other) to make it clearer, would be highly appreciated.

**Comment by gabejackson** [comment] 2013-12-29 16:24
The phrasing is not so much an issue, it is just located in the wrong place. I would clearly put this under the section "Installation" and also make a note that in such an environment memcached is required and the following setting must be used:

```
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
        'LOCATION': '127.0.0.1:11211',
    }
}
```

**Comment by aasensiog** [comment] 2014-01-15 12:25
As my colleague @gabejackson says in the comment above:

https://github.com/mbi/django-rosetta/issues/59#issuecomment-32357062

**Comment by crazyzubr** [comment] 2015-12-08 20:58
I have this problem. I propose to add the appropriate observation and problem solving in the [installation](http://django-rosetta.readthedocs.org/en/latest/installation.html) instructions.

**Comment by iMakedonsky** [comment] 2017-09-05 16:59
I support @crazyzubr with this suggestion. It should be mentioned in installation readme. @mbi
