### ISSUE TITLE
setting "ROSETTA_SHOW_AT_ADMIN_PANEL" not working

### ISSUE THREAD

**Issue by lc-thomas** [mbi/django-rosetta#178] opened 2017-01-05 07:28 UTC
- Which version of Django are you using?: 1.10.3
- Which version of django-rosetta are you using?: 0.7.12
- Have you looked trough [recent issues](https://github.com/mbi/django-rosetta/issues?utf8=%E2%9C%93&q=is%3Aissue) and checked this isn't a duplicate? yes I did.

I did put :  ROSETTA_SHOW_AT_ADMIN_PANEL = True  in my settings.
Nothing changed into administration, and I can't seem to access rosetta without editing the url.

Thank you for your time

**Comment by mbi** [comment] 2017-01-05 10:48
Yes, that's because that feature will only come in version [0.7.13 which hasn't been released yet](https://github.com/mbi/django-rosetta/blob/develop/CHANGES). 

I'm sorry, this is entirely my fault, because the online documentation already mentions this feature (the documentation is rebuilt from the dev branch each time a commit is pushed, I shouldn't merge feature branches until they're ripe for release).

**Comment by merwok** [comment] 2017-02-20 22:09
IMHO it’s better to have an active master, and let adventurous users try it, rather than blocking PRs and trying to merge them all in one shot.  It could make sense to have a stable branch (or the latest released tag) as default version on RTD, so that people can’t read the dev (master) docs without choosing so.

(Or do like Django and display a warning in the dev docs.)

**Comment by bittner** [comment] 2020-07-15 19:07
I can confirm this works in the current version (0.9.4).

This issue can probably be closed.

**Comment by mbi** [comment] 2020-07-15 19:22
Thanks for the heads-up, closing.

**Closed as completed by mbi** 2020-07-15 19:22 UTC
