### ISSUE TITLE
Problem on production server

### ISSUE THREAD

**Issue by artofhuman** [mbi/django-rosetta#56] opened 2012-11-16 06:24 UTC
Hi. on my production server i use MemcachedCache
And when i click link to select lang (/rosetta/select/en/0/) i redirect to home without form to edit translations

On my locale mac this work fine

**Comment by artofhuman** [comment] 2012-11-16 06:53
I try find problem and see line 351 in views.py storage.set('rosetta_i18n_fn',  file_)
After this i try logging 
logging.info(storage.get('rosetta_i18n_fn')) and its None. 
I think probmlem in 351 line storage cant set rosetta_i18n_fn param

**Comment by artofhuman** [comment] 2012-11-17 16:47
I install version 0.6.6
This version work fine

**Comment by mbi** [comment] 2013-01-15 12:57
Okay, this is most likely a dupe of #51

**Closed as completed by mbi** 2013-01-15 12:57 UTC
