### ISSUE TITLE
django 1.5a issue with 'rosetta-pick-file'

### ISSUE THREAD

**Issue by gbezyuk** [mbi/django-rosetta#57] opened 2012-11-23 18:33 UTC
TemplateSyntaxError at /rosetta/
Could not parse the remainder: '-pick-file' from 'rosetta-pick-file'
In template /flow/venv/local/lib/python2.7/site-packages/rosetta/templates/rosetta/languages.html, error at line 7

Looks like django 1.5 doesn't support this sort of url names.

**Comment by gbezyuk** [comment] 2012-11-23 18:39
Reason of this bug is this explained here: https://docs.djangoproject.com/en/dev/releases/1.5-alpha-1/#overview
One deprecated feature worth noting is the shift to “new-style” url tag. Prior to Django 1.3, syntax like {% url myview %} was interpreted incorrectly (Django considered "myview" to be a literal name of a view, not a template variable named myview). Django 1.3 and above introduced the {% load url from future %} syntax to bring in the corrected behavior where myview was seen as a variable.

So, solution is to put quotes around url names.

**Comment by gbezyuk** [comment] 2012-11-23 18:55
And also, param list for url should be divided with spaces instead of commas. Thus templates are to be corrected with:

```
<a href="{% url "rosetta-language-selection" lid forloop counter0 %} ...
```

instead of

```
<a href="{% url rosetta-language-selection lid forloop,counter0 %} ...
```

**Comment by mbi** [comment] 2013-01-09 13:19
This is likely a dupe of #46, cheers.

**Closed as completed by mbi** 2013-01-09 13:19 UTC
